name: da2023
channels:
  - pytorch
  - nvidia
  - conda-forge
  - astra-toolbox
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pylops
  - matplotlib
  - ipython
  - jupyter
  - cupy
  - pytorch==1.13.1
  - torchvision==0.14.1
  - torchaudio==0.13.1
  - pytorch-cuda=11.7
  - astra-toolbox
  - scikit-learn
  - tqdm
  - pip:
    - pyproximal
    - torchinfo
    - h5py
